# Generated by Django 3.2.9 on 2021-11-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('relation', models.CharField(choices=[('Friend', 'a friend'), ('Family', 'met as family'), ('Office', 'met at the office'), ('Stranger', 'A stranger')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
