# Generated by Django 3.2.9 on 2021-11-21 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cirkle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.contact'),
        ),
    ]
