# Generated by Django 3.2.9 on 2021-11-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='relation',
        ),
    ]
